---
- hosts: all
- hosts: localhost

  collections:
  - kubernetes.core
  - redhat.openshift.k8s

  tasks:
  - name: Get a list of all pods from any namespace
    kubernetes.core.k8s_info:
      kind: Pod
      namespace: ansible-automation-platform
    register: pod_list

  - name: Get Cluster information
    kubernetes.core.k8s_cluster_info:
    register: api_status

  - name: Show Cluster info
    ansible.builtin.debug:
      var: api_status.keys()
      
  - name: Search for all running pods
    kubernetes.core.k8s_info:
      kind: Pod
      field_selectors:
        - status.phase=Running
    register: pods

  - name: Show running pods
    ansible.builtin.debug:
      var: pods
