---
- hosts: all
- hosts: localhost

  collections:
  - kubernetes.core
  - redhat.openshift.k8s

  tasks:
  - name: Get a list of all pods from any namespace
    kubernetes.core.k8s_info:
      kind: Pod
      namespace: ansible-automation-platform
    register: pod_list

  - name: Get Cluster information
    kubernetes.core.k8s_cluster_info:
    register: api_status
